### ISSUE TITLE
VirtualBox Prompts for Login

### ISSUE THREAD

**Issue by kenetik** [last-box/LookingGlass#1]
Upon following the tutorials and instructions, after booting the VMDK it prompts for a login.

https://img.bi/#/KuWcxU3!6-rBuAvpHGHgwWnq2w3sI63gvExNigZZ9LdQYLkW

**Comment by packz** [comment]
You have to configure the stuffs by web interface

    8. Look for the IP address of the virtual server.

    Watch for the prompt on screen that says:

    >>> My Internet Protocol address is: ...

    9. In the address bar of your host's browser, enter the the IP address announced in the previous step - for example:

    http://10.0.0.69

    You don't have to access LG from the same host you run it on, but you do have to be on the same network.

**Comment by kenetik** [comment]
Thank you, that got me farther than previously. However, the "drive encryption" portion has taken well over 30 minutes at this point. (so much for 5~ minutes). 

Closing this out.

**Comment by packz** [comment]
I waited for several hours and it's not finished yet, I don't know if it's a problem or is it normal, I tried to used it locally but it's missing the python dependencies, probably I will open a issue later.

Also, are missing the script used to create the images, I would like to create one for a beaglebone black.

**Comment by packz** [comment]
I found something interesting @kenetik: from the source code seems that is waiting tor to be up and running; you can log in with the default credential (pi:raspberry) and do a ``sudo service tor start``.

**Comment by kenetik** [comment]
@pack That's definitely helpful and progress. Using that information I've been able to get all the way to 'http://redacted/setup/finished' ~ Now waiting a significant amount of time here:

    Please wait
    Give me a moment while I get things ready.
    
    Sorry about this, key creation is heavy lifting.

**Comment by packz** [comment]
Yeah, I'm also blocked there, if you look at the file ``/usr/local/bin/initialize-lg/30-gpg`` seems to be waiting for the mounting of a partition named ``gnupg`` but I don't understand where this should happen.

**Comment by packz** [comment]
I done some work with the code and I'm partially able to install it from scratch (bad enough I haven't yet  completed the configuration) and if someone is interested there is the ``experiments`` branch in my fork.
